import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { getSiteConfig } from '@/data-provider/pageService/getSiteConfig';
import { UiHeader } from '@/ui/components/UiHeader/UiHeader';
import { UiFooter } from '@/ui/components/UiFooter/UiFooter';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteConfig = await getSiteConfig();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UiHeader {...siteConfig.header} />
        {children}
        <UiFooter {...siteConfig.footer} />
      </body>
    </html>
  );
}
